<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE cesur[
    <!ELEMENT centro (alumnos, profesores) >
    <!ELEMENT alumnos (alumno+) >
    <!ELEMENT alumno (contacto, info) >
    
    <!ELEMENT contacto ( nombre, apellidos ) >
    <!ELEMENT nombre (#PCDATA) >
    <!ELEMENT apellidos (#PCDATA) >
    
    <!ELEMENT info (ciclo, matriculacion, modulo+) >
    <!ELEMENT ciclo (#PCDATA) >
    <!ELEMENT matriculacion (#PCDATA) >
    <!ELEMENT modulo (nombre, ciclo?) >
    
    <!ELEMENT profesores (profesor+) >
    <!ELEMENT profesor (contacto, modulo+) >
    
]>


<centro>
    
    <alumnos>
        <alumno>
            
            <contacto>
                <nombre></nombre>
                <apellidos></apellidos>
            </contacto>
            
            <info>
                <ciclo></ciclo>
                <matriculacion></matriculacion>
                <modulo>
                    <nombre></nombre>
                    <ciclo></ciclo>
                </modulo>
            </info>
        </alumno>
    </alumnos>
    
    <profesores>
        <profesor>
            <contacto>
                <nombre></nombre>
                <apellidos></apellidos>
            </contacto>
            <modulo>
                <nombre></nombre>
                <ciclo></ciclo>
            </modulo>
        </profesor>
    </profesores>
</centro>

