<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->

<!DOCTYPE documento [

<!ELEMENT documento (html) >
<!ELEMENT html (head, body) >
<!ELEMENT head (title) >
<!ELEMENT body (h1 | h2 | h3 | h4 | p | ul | ol | hr | a | img)* >
<!ELEMENT title (#PCDATA) >
<!ELEMENT a (#PCDATA | href) >
<!ELEMENT p (#PCDATA | a | strong | br)* >
<!ELEMENT h1 (#PCDATA | a | strong | br)* >
<!ELEMENT h2 (#PCDATA | a | strong | br)* >
<!ELEMENT h3 (#PCDATA | a | strong | br)* >
<!ELEMENT h4 (#PCDATA | a | strong | br)* >
<!ELEMENT img (width | height | src) >
<!ELEMENT ul (li)+ >
<!ELEMENT ol (li)+ >
<!ELEMENT li (#PCDATA | a | strong | br)* >
<!ELEMENT strong (#PCDATA) >
<!ELEMENT br EMPTY >
<!ELEMENT hr EMPTY >

]>

<documento>
	<html>
		<head>
			<title>Documento html</title>
		</head>
		
		<body>
			<h1>TITULO DE EJEMPLO</h1>
			<h2>SUBTITULO DE EJEMPLO</h2>
			<h3>blablacar</h3>
			<h4>Chukwueze</h4>
			<p>Este p√°rrafo contiene un <a href="#">enlace</a> </p>
			<p>Parrafo con imagen <img width="50" height="50" src="#"/></p>
			<p>Lista de la compra:(lo importante en negrita)</p>			
			<ul>
				<li>comprar zanahorias</li>
				<li><strong>comprar papel higienico</strong></li>
			</ul>
			<ol>
				<li>Fernando Alonso</li>
				<li>Max Verstappen</li>
			</ol>
			<hr></hr>
			
		</body>
	</html>
</documento>
